version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libnss3-tools
      - run: mvn verify